### ISSUE TITLE
相当给力的项目，最近我也在研究这块东西，请问您觉得instagram用的是什么方案？

### ISSUE THREAD

**Issue by xu6148152** [ongakuer/CameraFilter#1]
我反编译了他们的APK，发现他们android声明文件里面有opengl的声明，那应该是用opengl，但他们并没有限制4.3以上设备能使用。因此估计不能使用 grafika方案。然后看了下它们的.so文件，发现都很小，不知道是不是自己写的编码器，引用ffmpeg似乎会很大。感觉它们这块做得相当好。

**Comment by ongakuer** [comment]
不知道，低版本支持大部分都是ffmpeg吧。

**Comment by xu6148152** [comment]
ffmpeg so文件会比较大，他们有可能是自己写的编码解码。
